apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: centosapp
  name: node-deployment-nautilus
  namespace: node-namespace-nautilus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: centosapp
  template:
    metadata:
      labels:
        app: centosapp
    spec:
      containers:
      - image: gcr.io/kodekloud/centos-ssh-enabled:node
        name: node-container-nautilus
        ports:
         - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: node-service-nautilus
  namespace: node-namespace-nautilus
spec:
  type: NodePort
  selector:
    app: centosapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30012


