apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tomcat-deployment-xfusion
  name: tomcat-deployment-xfusion
  namespace: tomcat-namespace-xfusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-deployment-xfusion
  template:
    metadata:
      labels:
        app: tomcat-deployment-xfusion
    spec:
      containers:
      - image: gcr.io/kodekloud/centos-ssh-enabled:tomcat
        name: centos-ssh-enabled
        ports:
         - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service-xfusion
  namespace: tomcat-namespace-xfusion
spec:
  type: NodePort
  selector:
    app: tomcat-deployment-xfusion
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30007


